SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

# Asteroid Constants
ASTEROID_MAX_RADIUS = 50
ASTEROID_MIN_RADIUS = 10
ASTEROID_KINDS = 3 # For different sizes/types of asteroids
ASTEROID_SPAWN_RATE = 1.0 # Seconds between new asteroid spawns